spring:
  flyway:
    locations: classpath:db/migration
  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/test
    password: test
    username: test
    driver-class-name: org.postgresql.Driver


mybatis:
  configuration:
    map-underscore-to-camel-case: true

